### ISSUE TITLE
Probleme durch terminal Installation bei Folge-Installationen ioBroker

### ISSUE THREAD

**Issue by testit2020** [ioBroker/ioBroker.terminal#10]
Fehler mit authenticate-pam
Abhängigkeit im iobroker
iobroker.inst@2.0.3 /opt/iobroker
--
  | └─┬ iobroker.terminal@0.1.2
  | └── UNMET OPTIONAL DEPENDENCY authenticate-pam@1.0.2

Fehler 

https://forum.iobroker.net/topic/38459/gel%C3%B6st-warn-bei-allen-adapter-neu-inst-authenticate_pam

**Comment by sbormann** [comment]
Same for me. Can't we remore authenticate-pam from dependencies? Is it needed?

**Comment by Apollon77** [comment]
Closing, it is an optional dependenc, so no issue at all ...
