### ISSUE TITLE
terminal adapter fails to start

### ISSUE THREAD

**Issue by fenderlein** [ioBroker/ioBroker.terminal#12]
The adapter is always terminated on start-up, restart aso.
There is no chance to get it running.

`<html>
<body>

terminal.0 | 2021-12-10 15:23:24.547 | info | https server listening on port 8085
-- | -- | -- | --
terminal.0 | 2021-12-10 15:23:24.542 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
terminal.0 | 2021-12-10 15:23:24.540 | info | terminating
terminal.0 | 2021-12-10 15:23:24.522 | error | io.listen is not a function
terminal.0 | 2021-12-10 15:23:24.521 | error | TypeError: io.listen is not a function at initialize (/opt/iobroker/node_modules/iobroker.terminal/lib/web-terminal/lib/terminal.js:162:13) at initWebServer (/opt/iobroker/node_modules/iobroker.terminal/main.js:310:9) at Immediate.<anonymous> (/opt/iobroker/node_modules/iobroker.terminal/main.js:103:25) at processImmediate (internal/timers.js:466:21)
terminal.0 | 2021-12-10 15:23:24.519 | error | uncaught exception: io.listen is not a function
terminal.0 | 2021-12-10 15:23:24.253 | info | starting. Version 0.1.2 in /opt/iobroker/node_modules/iobroker.terminal, node: v14.18.2, js-controller: 3.3.21

</body>
</html>`

What can I do the make it run? 

Thanks.

**Comment by fenderlein** [comment]
Hi,
I installed the adapter on a second machine. There are some warnings coming up during the installation:

pi@raspberrypi:~ $ iobroker install terminal
NPM version: 6.14.15
npm install iobroker.terminal@0.1.2 --loglevel error --prefix "/opt/iobroker" (System call)
../authenticate_pam.cc: In function ‘void after_doing_auth(uv_work_t*, int)’:
../authenticate_pam.cc:107:87: warning: ‘v8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*)’ is deprecated [-Wdeprecated-declarations]
   Nan::MakeCallback(Nan::GetCurrentContext()->Global(), Nan::New(m->callback), 1, args);
                                                                                       ^
In file included from ../authenticate_pam.cc:23:
../../nan/nan.h:1028:46: note: declared here
   NAN_DEPRECATED inline v8::Local<v8::Value> MakeCallback(
                                              ^~~~~~~~~~~~
../authenticate_pam.cc:107:87: warning: ‘v8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*)’ is deprecated [-Wdeprecated-declarations]
   Nan::MakeCallback(Nan::GetCurrentContext()->Global(), Nan::New(m->callback), 1, args);
                                                                                       ^
In file included from ../authenticate_pam.cc:23:
../../nan/nan.h:1028:46: note: declared here
   NAN_DEPRECATED inline v8::Local<v8::Value> MakeCallback(
                                              ^~~~~~~~~~~~
In file included from ../../nan/nan.h:58,
                 from ../authenticate_pam.cc:23:
../authenticate_pam.cc: At global scope:
/home/iobroker/.cache/node-gyp/14.18.2/include/node/node.h:787:43: warning: cast between incompatible function types from ‘void (*)(v8::Local<v8::Object>)’ to ‘node::addon_register_func’ {aka ‘void (*)(v8::Local<v8::Object>, v8::Local<v8::Value>, void*)’} [-Wcast-function-type]
       (node::addon_register_func) (regfunc),                          \
                                           ^
/home/iobroker/.cache/node-gyp/14.18.2/include/node/node.h:821:3: note: in expansion of macro ‘NODE_MODULE_X’
   NODE_MODULE_X(modname, regfunc, NULL, 0)  // NOLINT (readability/null_usage)
   ^~~~~~~~~~~~~
../authenticate_pam.cc:188:1: note: in expansion of macro ‘NODE_MODULE’
 NODE_MODULE(authenticate_pam, init);
 ^~~~~~~~~~~
host.raspberrypi install adapter terminal
upload [1] terminal.admin /opt/iobroker/node_modules/iobroker.terminal/admin/terminal.png terminal.png image/png
upload [0] terminal.admin /opt/iobroker/node_modules/iobroker.terminal/admin/index.html index.html text/html
upload [0] terminal /opt/iobroker/node_modules/iobroker.terminal/www/login/index.html login/index.html text/html
host.raspberrypi object system.adapter.terminal created/updated
host.raspberrypi object connected created/updated

**Comment by marlan99** [comment]
same problem here on 1 Raspberry system while its working on 2 others on the same OS and ioBroker version.
It seems that this adapter is deprecated anyway?

i tried now https://github.com/ioBroker/ioBroker.xterm and its working on all three systems.
Right now only available on the beta channel

**Comment by Apollon77** [comment]
DIe Warnungen sind an sich egal ... ist halt npm
