### ISSUE TITLE
adapter not starting "port already in use"

### ISSUE THREAD

**Issue by reutli** [ioBroker/ioBroker.terminal#19]
**Describe the bug**  
after updated all adapters in iobroker this adapter is not starting anymore with error "port xxxx already in use".

**Expected behavior**  
adapter should start automatically.

**Screenshots & Logfiles**  
```
terminal.0 | 4181 | 2022-04-02 12:32:07.162 | error | port 8081 already in use
-- | -- | -- | -- | --
terminal.0 | 4181 | 2022-04-02 12:32:06.918 | info | starting. Version 0.2.1 in /opt/iobroker/node_modules/iobroker.terminal, node: v14.19.0, js-controller: 4.0.21
host.macmini-iobroker |   | 2022-04-02 12:32:05.684 | info | instance system.adapter.terminal.0 started with pid 4181
```

**Versions:**  
 - Adapter version: 0.2.1
 - JS-Controller version: 4.0.2
 - Node version: 14.19.0
 - Operating system: Debian

**Additional context**  
Tried to use antother port --> same failure

**Comment by Apollon77** [comment]
which other port you choose? YOu need to make sure to use one not already used by other adapters

**Comment by reutli** [comment]
I tried six or seven different ports (8050, 8090, 8020, ....) all not in use...

**Comment by Apollon77** [comment]
and the error always says "port 8081 alreayd in use"? Or is the error alsw<ys stating the port which is set?
Please try to run "iob fix" when on linux

**Comment by Apollon77** [comment]
And BTW: js.controller 4.0.2??? Really? Such a very early alpha test version? Please upgrade to 4.0.21

**Comment by reutli** [comment]
> and the error always says "port 8081 alreayd in use"? Or is the error alsw<ys stating the port which is set?
> Please try to run "iob fix" when on linux

Yes tried just a few seconds ago...
states the port which is set for each:
```
terminal.0 | 18761 | 2022-04-02 17:16:03.391 | error | port 8081 already in use
-- | -- | -- | -- | --
terminal.0 | 18761 | 2022-04-02 17:16:03.148 | info | starting. Version 0.2.1 in /opt/iobroker/node_modules/iobroker.terminal, node: v14.19.0, js-controller: 4.0.21
```


```
terminal.0 | 20898 | 2022-04-02 17:17:07.504 | error | port 8050 already in use
-- | -- | -- | -- | --
terminal.0 | 20898 | 2022-04-02 17:17:07.462 | info | starting. Version 0.2.1 in /opt/iobroker/node_modules/iobroker.terminal, node: v14.19.0, js-controller: 4.0.21
```

js-controller is at 4.0.21, see above.
"iob fix" already ran...

**Comment by reutli** [comment]
ok, I did the trick...
I've deleted the adapter completely and reinstalled again.
No it's up&running as it should.

...embarrassing that I didn't try that right away.

But, as the error occurred after made some updates this could be a bug, couldn't it?

**Comment by Apollon77** [comment]
wtihout seeng logs from your system and digging in deep no chance ... code looks good and when it says "port already used" then this should be "true". Please open issue again if it happens again

**Comment by reutli** [comment]
> wtihout seeng logs from your system and digging in deep no chance ... code looks good and when it says "port already used" then this should be "true". Please open issue again if it happens again

sure, will do so. As nobody opened an issue like me it seems to be an individual case.
thanks for listening ;o)
