### ISSUE TITLE
terminal Adapter does not start after update to 0.2.1

### ISSUE THREAD

**Issue by cdaerr** [ioBroker/ioBroker.terminal#20]
**Describe the bug**  
After update to Version 0.2.1 the adapter does not start properly:
![grafik](https://user-images.githubusercontent.com/98185044/161417107-63c9436f-5a22-4050-8200-0d8c3b7e1e0d.png)

**Screenshots & Logfiles**  
![grafik](https://user-images.githubusercontent.com/98185044/161417030-8bcabe00-32b3-4e8b-ae6c-2916bade2b89.png)

**Versions:**  
 - Adapter version: 0.2.1
 - JS-Controller version: 4.0.15
 - Node version: v14.19.1
 - Operating system: ubuntu 20.04 LTS

**Comment by Apollon77** [comment]
Please try to reboot your host or restsart ipbroker completely. Somehow he detects the ports as used

**Comment by cdaerr** [comment]
This was my first try, the second was changeing the port, wich ca be ssen in the Screenshot. Nothing worked.

**Comment by Apollon77** [comment]
DId you do what I posted?

**Comment by Apollon77** [comment]
Ok, I saw somethign strange in the coe. Can you pleasebtry GitHub version if better?

**Comment by cdaerr** [comment]
No, same issue. But it works well after downgrading to 0.1.2:
![grafik](https://user-images.githubusercontent.com/98185044/161605577-a55ffdf4-fb46-4606-9712-868e6832b7da.png)

**Comment by Apollon77** [comment]
Please try Github version again. I think I found it

**Comment by cdaerr** [comment]
Yes it works now.

Thanks
