### ISSUE TITLE
ctrl + c not functional

### ISSUE THREAD

**Issue by GottZ** [ioBroker/ioBroker.terminal#21]
**Describe the bug**  

**To Reproduce**  
1. ping google.de
2. ctrl + c

**Expected behavior**  
termination of ping execution

**Screenshots & Logfiles**  
![image](https://user-images.githubusercontent.com/559564/164559735-d26299c5-7170-4f31-95b5-1759ecb7b076.png)
(killed through a different shell using htop)

**Versions:**  
 - Adapter version: 0.2.2
 - JS-Controller version: 4.0.21
 - Node version: v14.19.1
 - Operating system: docker: buanet/iobroker:latest-v6

**Additional context**  
It is impossible to type in new commands while the ping is running.

**Comment by GottZ** [comment]
ok so this is where the signals are handled in the backend.

https://github.com/ioBroker/ioBroker.terminal/blob/18b25fb00c44ce851bac8677b0711369bd7889f0/lib/web-terminal/lib/terminal.js#L276-L296

and this is where the signals are emitted from the frontend to the backend.

https://github.com/ioBroker/ioBroker.terminal/blob/18b25fb00c44ce851bac8677b0711369bd7889f0/lib/web-terminal/web/init.js#L373-L389


67 is indeed ctrl + c and 68 is ctrl + d.
notice how ever that ctrl + d is used to save your current website as bookmark to the browser.

**Comment by GottZ** [comment]
![image](https://user-images.githubusercontent.com/559564/164644905-505d7955-a387-48c3-bb5d-314ed11c8847.png)
SIGINT is submitted to the backend on pressing ctrl + c but seems to be unable to interrupt the currently running process.
SIGQUIT how ever is not emitted at all. (current microsoft edge.. basically chrome)

**Comment by GottZ** [comment]
ok so apparently replacing
https://github.com/ioBroker/ioBroker.terminal/blob/18b25fb00c44ce851bac8677b0711369bd7889f0/lib/web-terminal/lib/terminal.js#L293
with
```javascript
socket.emit("console", `killing ${proc.pid} with signal ${signal} ${proc.kill(signal) ? "succeeded" : "failed"}`);
```
does indicate that the kill succeeds.

```
/opt/iobroker$ sleep 5

^C
killing 2536 with signal SIGINT succeeded
^C
killing 2536 with signal SIGINT succeeded
^C
killing 2536 with signal SIGINT succeeded
^C
killing 2536 with signal SIGINT succeeded
^C
killing 2536 with signal SIGINT succeeded
^C
killing 2536 with signal SIGINT succeeded
^C
killing 2536 with signal SIGINT succeeded
^C
killing 2536 with signal SIGINT succeeded
^C
killing 2536 with signal SIGINT failed
^C
killing 2536 with signal SIGINT failed
^C
killing 2536 with signal SIGINT failed
^C
killing 2536 with signal SIGINT failed
```



I assume sigint just does not propagate through `sh -c`
Let's see if that is true:

ping google.de in one console.
ps aux returns this:
```
iobroker    2809  0.0  0.0   2420   588 ?        S    11:22   0:00 /bin/sh -c ping google.de
iobroker    2810  0.0  0.0   7656  2464 ?        S    11:22   0:00 ping google.de
```

the SIGINT will be sent to pid 2809.
executing kill -2 2809 yields the same effect, and does not stop the ping.

I assumed this Problem was fixed.. Last time I had to deal with this issue was around 2014 and I hoped it was fixed by now.

related issues with workarounds:

https://github.com/nodejs/node/issues/40438

https://github.com/sindresorhus/execa/issues/96

From my experience the problem boils down to using sh as wrapper for executing commands that could technically be executed without it.

This Terminal Plugin should probably just abandon this legacy terminal thing and move over to something like https://github.com/microsoft/node-pty with https://github.com/xtermjs/xterm.js as frontend (vscode uses it)

I technically could fix the problems of this plugin here but why do so, if a better dependency exists.

want me to try refactoring this?

**Comment by Apollon77** [comment]
Hi,

We already have an xterm adapter you might want to try out which should base exactly on that ... SO for terminal I would also be happy for a PR for a fix, but would not refacter too much. because maybe xterm is a better way for the future

**Comment by GottZ** [comment]
![image](https://user-images.githubusercontent.com/559564/164718831-16699975-433c-418a-be9e-93d4b078d61a.png)
xterm doesn't seem to be in the stable repo. is there anything blocking it from getting there?
I consider ioBroker.terminal completely deprecated now that I know this.

I'll play a bit with it to fix ctrl + c tho.

**Comment by Apollon77** [comment]
xterm is in beta repo ... on a list to bring to stable tho. You can install from beta (Admin - enable expert mode - custom install button - install from npm)

**Comment by Apollon77** [comment]
@GottZ So after reading all the input I think the "Only" solution that makes sense to me would be to use https://github.com/simonepri/pidtree with proc.pid and then kill all that came back there. WHat do you think?

**Comment by GottZ** [comment]
Oh that's dirty! I like it.
Yep that should indeed work.

**Comment by Apollon77** [comment]
Do you want to test it :-) GitHub is updated ... please restart adapter once after update

**Comment by GottZ** [comment]
nice. it works flawless on linux.
I guess this solves this Issue then.
Moving to xterm now.
