### ISSUE TITLE
GUI issue

### ISSUE THREAD

**Issue by XxJooO** [ioBroker/ioBroker.terminal#9]
![image](https://user-images.githubusercontent.com/47712364/96283690-de326b00-0fdc-11eb-94fc-436605a3ec52.png)

Please check forum address:

https://forum.iobroker.net/topic/37687/anzeigefehler-der-web-oberfl%C3%A4che

**Comment by Apollon77** [comment]
Please retry ... works for me ... testin Admin 5 please
